encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "WIKI"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:prefix>", views.title, name="title"),
    path("find/wiki/", views.search, name="search"),
    path("new/wiki", views.create_entry, name="create_entry"),
    path("random/wiki/", views.random_entry, name="random"),
    path("edits/wiki/<str:prefix>", views.edit_entry, name="edit")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
    # path('entries/', include("wiki.urls"))

]

encyclopedia/models.py
from django.db import models
# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from . import util
from django.http import HttpResponse
from .myform import NewWikiForm, EditWikiForm
from random import randint


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


# renders a content from title of pass in args
def title(request, prefix):
    title = prefix.lower()
    content = util.get_entry(prefix)
    if content is not None:
        return render(request, "encyclopedia/entrypage.html", {
        "title": title,
        "content": util.converts_md_to_html(content)
        })

    else:
        return render(request, 'encyclopedia/err.html', {
        'msg': ' status:404, encyclopedia doesn\'t exist.' 
        })



def search(request):
    if request.method == "POST":
        query = request.POST["q"].lower()
        # If query is empty string
        if query == "":
            return render(request, "encyclopedia/search.html", {
            "query": query,
            "search_result": None
            })


        # If queried, check if query is substring of an existing wiki
        saved_entries = [x.lower() for x in util.list_entries()]
        matching_entries = [s.lower() for s in saved_entries if query in s]

        # checks if query perfectly matches a wiki
        if len(matching_entries) == 1 and query == matching_entries[0]:
            return render(request, "encyclopedia/entrypage.html", {
                "title": query,
                "content": util.converts_md_to_html(util.get_entry(query))
            })
        # validates If query is not part of an existing wiki
        else:
            print(f"testing {matching_entries}")
            return render(request, "encyclopedia/search.html", {
            "query": query,
            "search_results": matching_entries if len(matching_entries) >= 1 else None
            })
    return render(request, "encyclopedia/err.html", {
        "msg": "Sorry can't find your query try something else"
    })


# Handles wiki entry creation (with Django Forms)
def create_entry(request):
    if request.method == "POST":
        new_entry_form = NewWikiForm(request.POST)
        if new_entry_form.is_valid():
            saved_entries = saved_entries = [x.lower() for x in util.list_entries()]
            entry_title = new_entry_form.cleaned_data["entry_title"].lower()
            if entry_title in saved_entries:
                return render(request, "encyclopedia/err.html", {
                    "msg": "Failed to publish new entry (already exists in Wiki database)."
                })
            # Save entry to disk and redirect user to new entry's page
            entry_description = new_entry_form.cleaned_data["entry_description"]
            util.save_entry(entry_title, entry_description)
            return render(request, "encyclopedia/entrypage.html", {
                "title": entry_title,
                "content": util.converts_md_to_html(util.get_entry(entry_title))
            })


            # If form is not valid
        else:
            return render(request, "encyclopedia/newentry.html",{
            "new_entry_form": NewWikiForm()
            })
    
    return render(request, "encyclopedia/newentry.html", {
            "new_entry_form": NewWikiForm()
        })



# Handles returning of a random entry page
def random_entry(request):
    saved_entries = util.list_entries()
    random_int = randint(0, len(saved_entries) - 1)
    random_entry = saved_entries[random_int].lower()

    print(random_entry)
    return render(request, "encyclopedia/entrypage.html", {
        "title": random_entry,
        "content": util.converts_md_to_html(util.get_entry(random_entry))
    })





# Handles entry editing
def edit_entry(request, prefix):

    # If GET request is invoke
    if request.method == "GET":
        if prefix is not None:
            entry_description = util.get_entry(prefix)
            initial = {'entry_description': entry_description}
            return render(request, "encyclopedia/edit.html", {
                "title": prefix.lower(),
                "edit_form": EditWikiForm(initial=initial)
            })
        else:
            return render(request, "encyclopedia/err.html", {
            "msg": "Hmm, something went wrong."
        })
    # else it is POST request
    else:
        edit_form = EditWikiForm(request.POST)
        if edit_form.is_valid():
            new_description = edit_form.cleaned_data["entry_description"]
            util.save_entry(prefix.capitalize(), str(new_description))
            title = prefix.lower()
            content = util.get_entry(prefix)
            return render(request, "encyclopedia/entrypage.html", {
                "title": title,
                "content": util.converts_md_to_html(content)
            })
        # If form is not valid
        else:
            return render(request, "encyclopedia/err.html", {
                "msg": "Hmm, something went wrong."
            })

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}Edit entry{% endblock %}

{% block body %}
    <h1>Edit {{ title|capfirst }} Wiki </h1>
    <form action="{% url 'WIKI:edit' title %}" method="POST">
        
        <div>

            {{ edit_form.entry_description.label_tag }} 
            <br/> 
        
        <code>{{ edit_form.entry_description }}</code>
            <br/>
            {% csrf_token %}
        <button type="submit" class="btn btn-danger">Commit changes!</button>
    </div>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entrypage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title|capfirst}}
{% endblock %}
<br>


{% block body %}
 <div> {{ content|safe }} <div>

<br/>
<div>
   <form action="{% url 'WIKI:edit' title %}" method="GET">
    {% csrf_token %}
       <button type="submit" class="btn btn-primary">edit wiki?</button>
   </form>
</div>
{% endblock %}

encyclopedia/templates/encyclopedia/err.html
{% extends "encyclopedia/layout.html" %}

{% block title %}Error{% endblock %}

{% block body %}
<h1>{{ msg }}</h1>
<a href="{% url 'WIKI:index' %}"> Go Back?</a>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li> <a href="{% url 'WIKI:title' entry %}">{{ entry|capfirst }} </a> </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'WIKI:search' %}"  method="POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'WIKI:index' %}">Home</a>
                </div>
                <div>
                   <a href="{% url 'WIKI:create_entry' %}"> Create New Wiki </a>
                </div>
                <div>
                    <a href="{% url  'WIKI:random' %}"> Visit Random Wiki </a>
                    
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newentry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}Create new entry{% endblock %}

{% block body %}
    <h1>New Wiki</h1>
    <form action="{% url 'WIKI:create_entry' %}" method="POST">
        {% csrf_token %}
        {{ new_entry_form }}
        <br/>
        <button type="submit" class="btn btn-warning">Commit Page?</button>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Page
{% endblock %}



{% block body %}
    <h1>Your search Result for <q>{{ query }}</q> </h1>
    {% if search_results %}
    <ul>
        {% for result in search_results %}
            <li><a href="{% url 'WIKI:title' result|capfirst %}">{{ result|capfirst }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No results</p>
    {% endif %}
    <a href="{% url 'WIKI:index' %}"  >Go Back?</a>
{% endblock %}